apiVersion: batch/v1
kind: Job

metadata:
  name: smoke-test

spec:
  backoffLimit: 0

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: smoke-test
          image: cicd-sdet-tests:1
          imagePullPolicy: IfNotPresent
